name: workflow del ej 3

on: pull_request
permissions:
  security-events: write

jobs: 
  tarea2:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4

      - name: Linter. calidad del codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
        
